module.exports = {
	collectCoverage: true,
	coverageDirectory: 'coverage',
	clearMocks: true,
	moduleNameMapper: {
		'^.+\\.svg$': 'jest-svg-transformer',
		'\\.(css|less|sccs|sass)$': 'identity-obj-proxy',
		'@components(.*)$': '<rootDir>/src/components/$1',
		'^uuid$': 'uuid',
		'\\.(png|jpg|webp|ttf|woff|woff2|svg|mp4)$': '<rootDir>/src/assets/mocks/imgs/fileMock.js',
	},
	preset: 'ts-jest',
	coveragePathIgnorePatterns: ['/node_modules/'],
	coverageReporters: ['html', 'text', 'cobertura', 'lcov'],
	moduleDirectories: ['node_modules'],
	testEnvironment: 'jsdom',
	testMatch: ['**/?(*.)+(spec|test).ts?(x)'],
	testPathIgnorePatterns: ['/node_modules/'],
	transformIgnorePatterns: ['/node_modules/'],
	roots: ['<rootDir>/src'],
	transform: { '^.+\\.tsx?$': 'ts-jest' },
	setupFiles: ['jest-canvas-mock', './jest.setup.ts'],
	setupFilesAfterEnv: ['@testing-library/jest-dom'],
	moduleFileExtensions: ['js', 'ts', 'tsx', 'json'],
};
